var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_openinFB:!0,_getTitleRowData:function(){return{}},setOpenInFancyBox:function(a){this._openinFB=a;return this},setStatuses:function(a){this._statuses=a;return this},setPreSetData:function(a){this._preSetData=a;return this},getSearchCriteria:function(){var a,c,b;a=this;null===a._searchCriteria&&(a._searchCriteria={});c=!0;$(a.searchDivId).getElementsBySelector("[search_field]").each(function(d){d.hasClassName("datepicker")?(a._signRandID(d),b=jQuery("#"+
d.id).data("DateTimePicker").date(),a._searchCriteria[d.readAttribute("search_field")]=b):a._searchCriteria[d.readAttribute("search_field")]=$F(d);if($F(d)instanceof Array&&0<$F(d).size()||"string"===typeof $F(d)&&!$F(d).blank())c=!1});!0===c&&(a._searchCriteria=null);return this},refreshTaskRow:function(a){return this.refreshResultRow(a)},refreshResultRow:function(a){var c,b;(c=$(this.resultDivId).down("tbody"))||(c=$(this.resultDivId));(b=c.down(".item_row[item_id="+a.id+"]"))?b.replace(this._getResultRow(a,
!1).addClassName("item_row")):c.insert({top:this._getResultRow(a,!1).addClassName("item_row")});return this},_openURL:function(a){if(!0!==this._openinFB)return window.location=a,this;jQuery.fancybox({width:"95%",height:"95%",autoScale:!1,autoDimensions:!1,fitToView:!1,autoSize:!1,type:"iframe",href:a});return this},showTaskPage:function(a){return this._openURL("/task/"+(a&&a.id?a.id:"new")+".html?blanklayout=1")},showOrderDetailsPage:function(a){return a&&a.id?this._openURL("/orderdetails/"+a.id+
".html?blanklayout=1"):this},showCustomerDetailsPage:function(a){return a&&a.id?this._openURL("/customer/"+a.id+".html?blanklayout=1"):this},_updateDueDateCell:function(a,c){var b,d,f,e;b=moment().utc();d=c.retrieve("data");if(this._preSetData&&this._preSetData.noDueDateStatusIds&&0<=this._preSetData.noDueDateStatusIds.indexOf(a.status.id))return this;f=0>d.diff(b);!0===f&&c.up("td").addClassName("danger").writeAttribute("title","Overdued!!!");e=d.diff(b,"hours",!0).toFixed(1);24<Math.abs(e)?c.down(".left-time").update("<strong>"+
d.diff(b,"days")+"</strong> <small>Day(s)</small>"):(c.down(".left-time").update("<strong>"+e+"</strong> <small>Hr(s)</small>"),!0!==f&&c.up("td").removeClassName("danger").addClassName("warning").writeAttribute("title","About to be overdued"));return this},_actionTask:function(a,c){var b,d;b=this;b.postAjax(b.getCallbackId("actionTask"),a,{onSuccess:function(a,e){try{(d=b.getResp(e,!1,!0))&&d.item&&d.item.id&&(b.refreshResultRow(d.item),"function"===typeof c&&c(d))}catch(g){b.hideModalBox(),b.showModalBox('<strong class="text-danger">Error</strong>',
g)}}});return b},_preActionTask:function(a){var c,b,d,f,e;c=this;b=(new Element("div",{"class":"confirm-div"})).insert({bottom:new Element("div",{"class":"msg-div"})}).insert({bottom:(new Element("div",{"class":"form-group"})).insert({bottom:(new Element("label",{"class":"control-label"})).update(d="Reason for action: "+a.method)}).insert({bottom:new Element("textarea",{"class":"form-control","confirm-div":"comments",placeholder:d})})}).insert({bottom:(new Element("div")).insert({bottom:(new Element("div",
{"class":"btn btn-default"})).update("Cancel").observe("click",function(){c.hideModalBox()})}).insert({bottom:(new Element("div",{"class":"btn btn-danger pull-right"})).update("Comfirm").observe("click",function(){f=$(this).up(".confirm-div");f.down(".msg-div").update("");e=$F(f.down('[confirm-div="comments"]'));e.blank()?f.down(".msg-div").update(c.getAlertBox("","Please provide some reason.").addClassName("alert-danger")):(a.comments=e,c._actionTask(a,function(){c.hideModalBox()}))})})});c.hideModalBox();
c.showModalBox('<strong class="text-danger">Please Confirm</strong>',b);return c},_getTechCell:function(a){var c,b,d,f,e;c=this;b=a.technician&&a.technician.id?a.technician.person.fullname:"";d=(new Element("div",{"class":"row"})).update(f=(new Element("span",{"class":"col-xs-10 truncate"})).update(b)).insert({bottom:(new Element("div",{"class":"pull-right"})).setStyle("margin: 0 5px 0 0;").update(e=new Element("div",{"class":"btn-group btn-group-xs visible-xs visible-sm visible-md visible-lg"}))});
c._preSetData&&c._preSetData.noDueDateStatusIds&&0>c._preSetData.noDueDateStatusIds.indexOf(a.status.id)&&(b.blank()?e.insert({bottom:(new Element("span",{"class":"btn btn-primary",title:"Take this Task"})).update("Take").observe("click",function(){c._actionTask({taskId:a.id,method:"take"})})}):c._preSetData&&c._preSetData.meId&&c._preSetData.meId===a.technician.id&&(e.insert({bottom:(new Element("span",{"class":"btn btn-success dropdown-toggle","data-toggle":"dropdown","aria-expanded":"false"})).update(new Element("span",
{"class":"caret"}))}).insert({bottom:e=(new Element("ul",{"class":"dropdown-menu"})).insert({bottom:"3"!==a.status.id?(new Element("li")).update((new Element("a",{href:"javascript:void(0);"})).update("Start").observe("click",function(){c._actionTask({taskId:a.id,method:"start"})})):(new Element("li")).update((new Element("a",{href:"javascript:void(0);"})).update("Finish").observe("click",function(){c._actionTask({taskId:a.id,method:"finish"})}))}).insert({bottom:(new Element("li")).update((new Element("a",
{href:"javascript:void(0);"})).update("Release").observe("click",function(){c._actionTask({taskId:a.id,method:"release"})}))}).insert({bottom:new Element("li",{"class":"divider"})}).insert({bottom:(new Element("li")).update((new Element("a",{href:"javascript:void(0);"})).update('<strong class="text-danger">ON HOLD</strong>').observe("click",function(){c._preActionTask({taskId:a.id,method:"onHold"})}))}).insert({bottom:(new Element("li")).update((new Element("a",{href:"javascript:void(0);"})).update('<strong class="text-danger">CANCEL</strong>').observe("click",
function(){c._preActionTask({taskId:a.id,method:"cancel"})}))})}),e&&"3"===a.status.id&&(e.insert({top:new Element("li",{"class":"divider"})}),e.insert({top:(new Element("li")).update((new Element("a",{href:"javascript:void(0);"})).update("Build a Kit").observe("click",function(){c._openURL("/kit/new.html?taskid="+a.id+"&blanklayout=1")}))}))));b.blank()||f.writeAttribute("title",b);return d},_getResultRow:function(a,c){var b={me:this};b.tag=!0===b.isTitle?"th":"td";b.isTitle=c||!1;b.row=(new Element("tr",
{"class":"order_item "+(!0===b.isTitle?"":"btn-hide-row"),item_id:!0===b.isTitle?"":a.id})).store("data",a).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).insert({bottom:!0===b.isTitle?"Task No.":(new Element("a",{href:"javascript: void(0);",title:"view details"})).update(a.id).observe("click",function(){b.me.showTaskPage(a)})})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).insert({bottom:!0===b.isTitle?"Customer":(new Element("a",{href:"javascript: void(0);","class":"truncate",
title:a.customer.name})).update(a.customer.name).observe("click",function(){b.me.showCustomerDetailsPage(a.customer)})})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-2"})).insert({bottom:!0===b.isTitle?'Due Date<font class="pull-right">Time Left</font> ':b.dueDateCell=(new Element("div",{"class":"row"})).store("data",b.dueDateUTC=moment(b.me.loadUTCTime(a.dueDate))).insert({bottom:(new Element("div",{"class":"col-xs-6"})).update((new Element("small")).update(b.dueDateUTC.format("DD/MMM/YYYY hh:mm A")))}).insert({bottom:(new Element("div",
{"class":"col-xs-6  text-right"})).update((new Element("span",{"class":"left-time"})).update(""))})})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1",order_status:!0===b.isTitle?"":a.status.name,title:!0===b.isTitle?"":a.status.description})).insert({bottom:!0===b.isTitle?"Status":(new Element("span")).update(a.status.name)})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).insert({bottom:!0===b.isTitle?"Tech":b.me._getTechCell(a)})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-2 truncate"})).insert({bottom:!0===
b.isTitle?"Instructions":(new Element("a",{href:"javascript: void(0);",title:"click to view all"})).update(a.instructions.stripTags()).observe("click",function(){b.me.hideModalBox();b.me.showModalBox("<strong>Instructions for Task: "+a.id+"</strong>",a.instructions)})})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).insert({bottom:!0===b.isTitle?"No. Of Kits":(new Element("div")).insert({bottom:(new Element("div",{"class":"col-xs-8"})).update(a.noOfKits&&0<a.noOfKits?(new Element("a",
{href:"javascript: void(0);"})).update(a.noOfKits).observe("click",function(){b.me._openURL("/kits.html?nosearch=1&blanklayout=1&taskId="+a.id)}):"")}).insert({bottom:(new Element("div",{"class":"col-xs-4"})).update(b.me._preSetData&&b.me._preSetData.meId&&b.me._preSetData.meId===a.technician.id&&a.status&&"3"===a.status.id?(new Element("span",{"class":"btn btn-xs btn-success"})).insert({bottom:new Element("i",{"class":"fa fa-plus"})}).observe("click",function(){b.me._openURL("/kit/new.html?blanklayout=1&taskid="+
a.id)}):"")})})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-2"})).insert({bottom:!0===b.isTitle?"Created From":a.fromEntity&&a.fromEntity.orderNo?(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-xs-3"})).update(a.fromEntity.type)}).insert({bottom:(new Element("div",{"class":"col-xs-3",order_status:a.fromEntity.status.name})).update(a.fromEntity.status.name)}).insert({bottom:(new Element("a",{"class":"col-xs-6",href:"javascript: void(0);",title:"view details"})).update(a.fromEntity.orderNo).observe("click",
function(){b.me.showOrderDetailsPage(a.fromEntity)})}):""})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1 truncate"})).insert({bottom:!0===b.isTitle?"Created By":(new Element("div",{title:"By: "+a.createdBy.person.fullname+" @ "+moment(b.me.loadUTCTime(a.created)).format("DD/MMM/YYYY hh:mm A")})).insert({bottom:(new Element("div",{"class":"col-xs-12"})).update(a.createdBy.person.fullname)})})});b.dueDateCell&&b.me._updateDueDateCell(a,b.dueDateCell);return b.row},_initOrderSearchBox:function(){var a,
c;a=jQuery('[search_field="ord.id"]').select2({minimumInputLength:3,multiple:!0,ajax:{delay:250,url:"/ajax/getAll",type:"POST",data:function(b){return{searchTxt:"orderNo like ? and storeId = ?",searchParams:["%"+b+"%",jQuery("#storeId").attr("value")],entityName:"Order",pageNo:1,userId:jQuery("#userId").attr("value")}},results:function(b,a,f){c=[];b.resultData&&b.resultData.items&&b.resultData.items.each(function(a){c.push({id:a.id,text:a.orderNo,data:a})});return{results:c}}},cache:!0,formatResult:function(a){return a?
'<div class="row order_item"><div class="col-xs-3">'+a.data.orderNo+'</div><div class="col-xs-3" order_status="'+a.data.status.name+'">'+a.data.status.name+'</div><div class="col-xs-6"><small>'+(a.data.customer&&a.data.customer.name?a.data.customer.name:"")+"</small></div></div >":""},escapeMarkup:function(a){return a}});this._preSetData&&this._preSetData.order&&this._preSetData.order.id&&a.select2("data",[{id:this._preSetData.order.id,text:this._preSetData.order.orderNo,data:this._preSetData.order}]);
return this},_initTechSearchBox:function(){var a,c;a=jQuery('[search_field="techId"]').select2({minimumInputLength:3,multiple:!0,ajax:{delay:250,url:"/ajax/getAll",type:"POST",data:function(a){return{searchTxt:'personId in (select id from person p where concat(p.firstName, " ", p.lastName) like ? and storeId = ?)',searchParams:["%"+a+"%",jQuery("#storeId").attr("value")],entityName:"UserAccount",pageNo:1}},results:function(a,d,f){c=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){c.push({id:a.id,
text:a.person.fullname,data:a})});return{results:c}}},cache:!0,escapeMarkup:function(a){return a}});this._preSetData&&this._preSetData.technician&&this._preSetData.technician.id&&a.select2("data",[{id:this._preSetData.technician.id,text:this._preSetData.technician.person.fullname,data:this._preSetData.technician}]);return this},_initCustomerSearchBox:function(){var a,c;a=jQuery('[search_field="customer.id"]').select2({minimumInputLength:3,multiple:!0,ajax:{delay:250,url:"/ajax/getAll",type:"POST",
data:function(a){return{searchTxt:"name like ? and storeId = ?",searchParams:["%"+a+"%",jQuery("#storeId").attr("value")],entityName:"Customer",pageNo:1,userId:jQuery("#userId").attr("value")}},results:function(a,d,f){c=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){c.push({id:a.id,text:a.name,data:a})});return{results:c}}},cache:!0,escapeMarkup:function(a){return a}});this._preSetData&&this._preSetData.customer&&this._preSetData.customer.id&&a.select2("data",[{id:this._preSetData.customer.id,
text:this._preSetData.customer.name,data:this._preSetData.customer}]);return this},_initStatusSearchBox:function(){var a,c;a=[];this._preSetData&&this._preSetData.statuses&&this._preSetData.statuses.each(function(b){a.push(b.id)});this._statuses&&0<this._statuses.size()&&$$('[search_field="statusId"]').first()&&this._statuses.each(function(b){$$('[search_field="statusId"]').first().insert({bottom:c=(new Element("option",{value:b.id})).update(b.name)});0<=a.indexOf(b.id)&&c.writeAttribute("selected",
!0)});jQuery('[search_field="statusId"]').select2();return this},init:function(){var a;a=this;jQuery(".datepicker").datetimepicker({format:"DD/MM/YYYY"});a._initCustomerSearchBox()._initOrderSearchBox()._initTechSearchBox()._initStatusSearchBox();$("searchBtn").observe("click",function(){a.getSearchCriteria().getResults(!0,30)});return a}});