var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{manufactures:[],suppliers:[],productCategories:[],productStatuses:[],_nextPageColSpan:9,_autoLoading:!1,_getTitleRowData:function(){return{sku:"SKU",name:"Product Name",manufacturer:{name:"Brand"},supplierCodes:[{supplier:{name:"Supplier"},code:""}],stockOnHand:"SOH"}},_loadManufactures:function(a){this.manufactures=a;var c;c=$(this.searchDivId).down('[search_field="pro.manufacturerIds"]');this.manufactures.each(function(a){c.insert({bottom:(new Element("option",{value:a.id})).update(a.name)})});
return this},_loadProductStatuses:function(a){this.productStatuses=a;var c;c=$(this.searchDivId).down('[search_field="pro.productStatusIds"]');this.productStatuses.each(function(a){c.insert({bottom:(new Element("option",{value:a.id})).update(a.name)})});return this},_loadSuppliers:function(a){this.suppliers=a;var c;c=$(this.searchDivId).down('[search_field="pro.supplierIds"]');this.suppliers.each(function(a){c.insert({bottom:(new Element("option",{value:a.id})).update(a.name)})});return this},_loadCategories:function(a){this.categories=
a;var c;c=$(this.searchDivId).down('[search_field="pro.productCategoryIds"]');this.categories.sort(function(a,c){return a.namePath>c.namePath}).each(function(a){c.insert({bottom:(new Element("option",{value:a.id})).update(a.namePath)})});return this},_loadChosen:function(){jQuery(".chosen").select2({minimumResultsForSearch:Infinity});return this},_bindSearchKey:function(){var a;a=this;$$("#searchBtn").first().observe("click",function(c){a.getSearchCriteria().getResults(!0,a._pagination.pageSize)});
$("searchDiv").getElementsBySelector("[search_field]").each(function(c){c.observe("keydown",function(b){a.keydown(b,function(){$(a.searchDivId).down("#searchBtn").click()})})});return this},_getSupplierCodes:function(a,c){var b;b=[];a.each(function(a){b.push(!0===c?"Supplier":'<abbr title="Code: '+a.code+'">'+(a.supplier&&a.supplier.name?a.supplier.name:"")+"</abbr>")});return b.join(", ")},getResults:function(a,c,b,e){var d,f,h,g,k,l;d=this;f=a||!1;h=b||!1;g=$(d.resultDivId);!0===f&&(d._pagination.pageNo=
1);!0===h&&0<$$(".btn-show-more").length&&(d._autoLoading=!0,d._pagination.pageNo=1*d._pagination.pageNo+1);d._pagination.pageSize=c||d._pagination.pageSize;d.postAjax(d.getCallbackId("getItems"),{pagination:d._pagination,searchCriteria:d._searchCriteria},{onLoading:function(){jQuery("#"+d.searchDivId+" .btn").button("loading");jQuery("#"+d.searchDivId+" input").prop("disabled",!0);jQuery("#"+d.searchDivId+" select").prop("disabled",!0);!0===f&&g.update((new Element("tr")).update((new Element("td")).update(d.getLoadingImg())))},
onSuccess:function(a,b){try{if(k=d.getResp(b,!1,!0))$(d.totalNoOfItemsId).update(k.pageStats.totalRows),!0===f&&g.update(d._getResultRow(d._getTitleRowData(),!0).wrap(new Element("thead"))),g.getElementsBySelector(".paginWrapper").each(function(a){a.remove()}),(l=$(g).down("tbody"))||$(g).insert({bottom:l=new Element("tbody")}),k.items.each(function(a){l.insert({bottom:d._getResultRow(a).addClassName("item_row").writeAttribute("item_id",a.id)})}),!0!==d._singleProduct&&k.pageStats.pageNumber<k.pageStats.totalPages&&
g.insert({bottom:d._getNextPageBtn().addClassName("paginWrapper")}),!0===h&&0<$$(".btn-show-more").length?d.getResults(!1,d._pagination.pageSize,!0):(d._autoLoading=!1,d.hideModalBox(),jQuery("#"+d.searchDivId+" .btn").button("reset"),jQuery("#"+d.searchDivId+" input").prop("disabled",!1),jQuery("#"+d.searchDivId+" select").prop("disabled",!1))}catch(c){g.insert({bottom:d.getAlertBox("Error",c).addClassName("alert-danger")})}},onComplete:function(){!0!==h&&(jQuery("#"+d.searchDivId+" .btn").button("reset"),
jQuery("#"+d.searchDivId+" input").prop("disabled",!1),jQuery("#"+d.searchDivId+" select").prop("disabled",!1))}})},_getNextPageBtn:function(){var a,c;a=this;c=$("total-found-count").innerHTML;return(new Element("tfoot")).insert({bottom:(new Element("tr")).insert({bottom:(new Element("td",{colspan:a._nextPageColSpan,"class":"text-center"})).insert({bottom:(new Element("span",{"class":"btn btn-primary btn-show-more","data-loading-text":"Fetching more results ..."})).update("Next Page").observe("click",
function(){a._pagination.pageNo=1*a._pagination.pageNo+1;jQuery(this).button("loading");a.getResults(!1,a._pagination.pageSize,!1,!0)})}).insert({bottom:(new Element("span",{"class":"btn btn-warning btn-show-more","data-loading-text":"Fetching more results ..."})).update("<b>Show ALL Pages</b>").setStyle("margin-left: 10px; color: black;").observe("click",function(){1E3<c?a.showModalBox("Warning","<h3>There are "+c+" products for current search conditions. <br/>Please narrow down the search"):a.getResults(!1,
a._pagination.pageSize,!0)})})})})},_getResultRow:function(a,c){var b={me:this};b.tag=!0===b.isTitle?"th":"td";b.isTitle=c||!1;0!=a.totalOnHandValue&&0!=a.stockOnHand?(b.avgcost=a.totalOnHandValue/a.stockOnHand,b.avgcost=b.me.getCurrency(b.avgcost)):b.avgcost="N/A";b.row=(new Element("tr",{"class":!0===b.isTitle?"":"btn-hide-row",product_id:a.id})).store("data",a).insert({bottom:(new Element(b.tag,{"class":"sku",title:a.name})).addClassName("col-xs-1").insert({bottom:!0===b.isTitle?a.sku:(new Element("a",
{href:"/product/"+a.id+".html",target:"_BLANK","class":"sku-link truncate"})).update(a.sku)})}).insert({bottom:(new Element(b.tag,{"class":"product_name hidden-xs hide-when-info hidden-sm"})).addClassName("col-xs-2").insert({bottom:a.name})}).insert({bottom:(new Element(b.tag,{"class":"manufacturer hidden-xs hide-when-info hidden-sm",style:"width:5%"})).addClassName("col-xs-1").update(a.manufacturer?a.manufacturer.name:"")}).insert({bottom:(new Element(b.tag,{"class":"stock"})).addClassName("col-xs-7").update(!0===
b.isTitle?(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-xs-4",title:"Stock on Hand"})).update("SOH")}).insert({bottom:(new Element("div",{"class":"col-xs-4 ",title:"Total Stock On Hand Value"})).update("SOHV")}).insert({bottom:(new Element("div",{"class":"col-xs-4 ",title:"Average Cost"})).update("Average Cost")}):(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-xs-4",title:"Stock on Hand"})).update(a.stockOnHand)}).insert({bottom:(new Element("div",
{"class":"col-xs-4",title:"Total Stock on Hand Value"})).update(b.me.getCurrency(a.totalOnHandValue))}).insert({bottom:(new Element("div",{"class":"col-xs-4 ",title:"Average Cost"})).update(b.avgcost)}))}).insert({bottom:(new Element(b.tag,{"class":"text-right col-xs-1 "})).update(!0===b.isTitle?"":(new Element("span",{"class":"btn-group btn-group-xs"})).insert({bottom:(new Element("span",{"class":"btn btn-default",title:"Edit"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})}).observe("click",
function(){$(this).up(".item_row").replace(b.editEl=b.me._getEditPanel(a));b.editEl.getElementsBySelector(".form-control[save-item-panel]").each(function(a){a.observe("keydown",function(a){b.me.keydown(a,function(){b.editEl.down(".btn-success span").click()});return!1})})})}))});return b.row},_getEditPanel:function(a){var c,b,e,d,f,h;c=this;0!=a.totalOnHandValue&&0!=a.stockOnHand?(b=a.totalOnHandValue/a.stockOnHand,b=c.getCurrency(b)):b="N/A";return(new Element("tr",{"class":"save-item-panel info"})).store("data",
a).insert({bottom:(new Element("td",{"class":"form-group col-xs-1 "})).insert({bottom:(new Element("span",{"class":" sku"})).insert({bottom:a.sku})}).insert({bottom:new Element("input",{"class":"",type:"hidden","save-item-panel":"id",value:a.id})})}).insert({bottom:(new Element("td",{"class":"form-group col-xs-2 hidden-xs hide-when-info hidden-sm "})).insert({bottom:(new Element("span",{"class":"productname"})).insert({bottom:a.name})})}).insert({bottom:(new Element("td",{"class":"form-group col-xs-1 hidden-xs hide-when-info hidden-sm "})).insert({bottom:(new Element("span",
{"class":"brand"})).insert({bottom:a.manufacturer?a.manufacturer.name:""})})}).insert({bottom:(new Element("td",{"class":"form-group col-xs-7"})).update((new Element("div",{"class":"row"})).insert({bottom:(new Element("span",{"class":" col-xs-4 StockOnPO"})).insert({bottom:new Element("input",{"class":"form-control",name:"Stock on Hand","save-item-panel":"stockOnHand",placeholder:"Stock On Hand",type:"number",value:a.stockOnHand?a.stockOnHand:0})}).observe("keydown",function(a){e=$(this);c.keydown(a,
function(){e.up(".item_row").down('[save-item="totalOnHandValue"]').select()})}).observe("keyup",function(){e=$(this);d=e.up(".item_row").down('[save-item="totalOnHandValue"]');d.value=c.getCurrency(a.unitCost*$F(e.down("input")))}).observe("click",function(a){$(this).down("input").select()})}).insert({bottom:(new Element("span",{"class":" col-xs-4 totalOnHandValue"})).insert({bottom:new Element("input",{"class":"form-control",disabled:!0,name:"Total Stock on Hand Value","save-item":"stockOnHandValue",
placeholder:"Stock On Hand Value",type:"value",value:a.totalOnHandValue?c.getCurrency(a.totalOnHandValue):c.getCurrency(0)})}).observe("keydown",function(a){e=$(this);c.keydown(a,function(){e.up(".item_row").down('[save-item="stockOnOrder"]').select()})}).observe("click",function(a){$(this).down("input").select()}).observe("change",function(a){$(this).down("input").value=c.getCurrency(c.getValueFromCurrency($(this).down("input").value))})}).insert({bottom:(new Element("span",{"class":" col-xs-4 averagecost"})).insert({bottom:b})}))}).insert({bottom:(new Element("td",
{"class":"form-group text-right col-xs-1"})).insert({bottom:(new Element("span",{"class":"btn-group btn-group-sm"})).insert({bottom:(new Element("span",{"class":"btn btn-success",title:"Save"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-ok"})}).observe("click",function(){f=this;(h=c._saveItem(f,$(f).up(".save-item-panel"),"save-item-panel"))&&jQuery(".tooltip")&&jQuery(".tooltip").remove()})}).insert({bottom:(new Element("span",{"class":"btn btn-danger",title:"Delete"})).insert({bottom:new Element("span",
{"class":"glyphicon glyphicon-remove"})}).observe("click",function(){a.id?$(this).up(".save-item-panel").replace(c._getResultRow(a).addClassName("item_row").writeAttribute("item_id",a.id)):$(this).up(".save-item-panel").remove();jQuery(".tooltip")&&jQuery(".tooltip").remove()})})})})}});