DROP TABLE IF EXISTS `rmaitem`;
CREATE TABLE `rmaitem` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `storeId` int(10) NOT NULL DEFAULT '1',
  `RMAId` int(10) unsigned NOT NULL DEFAULT '0',
  `orderItemId` int(10) unsigned DEFAULT NULL,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `qty` int(10) unsigned NOT NULL DEFAULT '0',
  `receivingItemId` int(10) unsigned DEFAULT NULL,
  `unitCost` double(10,4) unsigned NOT NULL DEFAULT '0.0000',
  `itemDescription` varchar(255) NOT NULL DEFAULT '',
  `bstatus` varchar(30) NOT NULL DEFAULT '',
  `sstatus` varchar(30) NOT NULL DEFAULT '',
  `receivedDate` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `RMAId` (`RMAId`),
  KEY `receivingItemId` (`receivingItemId`),
  KEY `receivedDate` (`receivedDate`),
  KEY `orderItemId` (`orderItemId`),
  KEY `bstatus` (`bstatus`),
  KEY `sstatus` (`sstatus`),
  KEY `productId` (`productId`),
  KEY `createdById` (`createdById`),
  KEY `updatedById` (`updatedById`),
  KEY `qty` (`qty`),
  KEY `unitCost` (`unitCost`),
  KEY `storeId` (`storeId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;