var SalesTargetListPanelJs=new Class.create;
SalesTargetListPanelJs.prototype={_pageJs:null,_panelHTMLID:"",initialize:function(a){this._pageJs=a;this._panelHTMLID="SalesTargetListPanelJs_"+String.fromCharCode(65+Math.floor(26*Math.random()))+Date.now()},getListPanel:function(){return(new Element("div",{"class":"panel",id:this._panelHTMLID})).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Sales Target :")})},_getListItem:function(a,c){var b;targetrevenue=a.sales.targetrevenue?a.sales.targetrevenue:0;targetprofit=a.sales.targetprofit?
a.sales.targetprofit:0;b=(new Element("a",{"class":"list-group-item"})).store("data",a).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-6"})).update("Revenue(Incl.): <strong>"+this._pageJs.getCurrency(targetrevenue)+"</strong>")}).insert({bottom:(new Element("div",{"class":"col-sm-6"})).update("Profit(Incl.): <strong>"+this._pageJs.getCurrency(targetprofit)+"</strong>")})});c.insert({bottom:b});b=(new Element("a",{"class":"list-group-item"})).store("data",
a).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("Period:")}).insert({bottom:(new Element("div",{"class":"col-sm-4"})).update("<strong>"+moment(a.sales.dfrom).format("DD/MMM/YYYY")+"</strong>")}).insert({bottom:(new Element("div",{"class":"col-sm-1"})).update("<strong> To </strong>")}).insert({bottom:(new Element("div",{"class":"col-sm-4"})).update("<strong>"+moment(a.sales.dto).format("DD/MMM/YYYY")+"</strong>")})});c.insert({bottom:b});
b=(new Element("a",{"class":"list-group-item"})).store("data",a).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-6"})).update("Days Left : <strong>"+a.daysleft+"</strong>")}).insert({bottom:(new Element("div",{"class":"col-sm-6"})).update("Total Days : <strong>"+a.sales.dperiod+"</strong>")})});c.insert({bottom:b});b=(new Element("a",{"class":"list-group-item",style:"background-color:#f5f5f5"})).store("data",a).insert({bottom:(new Element("div",
{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-12"})).update("Sales Progress :")})});c.insert({bottom:b});todayAmount=a.today.totalAmount?a.today.totalAmount:0;todayPaid=a.today.totalPaid?a.today.totalPaid:0;todayMargin=a.today.totalMargin?a.today.totalMargin:0;b=(new Element("a",{"class":"list-group-item"})).store("data",a).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("")}).insert({bottom:(new Element("div",
{"class":"col-sm-3"})).update("Total Amt")}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("Paid Amt")}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("Margin")})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("Today(Incl.):")}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("<strong>"+this._pageJs.getCurrency(todayAmount)+"</strong>")}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("<strong>"+
this._pageJs.getCurrency(todayPaid)+"</strong>")}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("<strong>"+this._pageJs.getCurrency(todayMargin)+"</strong>")})});c.insert({bottom:b});totalAmount=a.period.totalAmount?a.period.totalAmount:0;totalPaid=a.period.totalPaid?a.period.totalPaid:0;totalMargin=a.period.totalMargin?a.period.totalMargin:0;b=(new Element("a",{"class":"list-group-item"})).store("data",a).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",
{"class":"col-sm-3"})).update("Total(Incl.):")}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("<strong>"+this._pageJs.getCurrency(totalAmount)+"</strong>")}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("<strong>"+this._pageJs.getCurrency(totalPaid)+"</strong>")}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update("<strong>"+this._pageJs.getCurrency(totalMargin)+"</strong>")})});c.insert({bottom:b});return c},showList:function(){var a,c,b,d;a=this;
if(!$(a._panelHTMLID))return a;c=(new Element("div",{"class":"panel-body"})).update(a._pageJs.getLoadingImg());new Ajax.Request("/ajax/getSalesTarget",{method:"get",parameters:{pageNo:1,pageSize:30},onCreate:function(){$(a._panelHTMLID).insert({bottom:c})},onSuccess:function(c){try{(b=a._pageJs.getResp(c.responseText,!1,!0))&&b.items&&($(a._panelHTMLID).down("panel-body")&&$(a._panelHTMLID).down("panel-body").remove(),(d=$(a._panelHTMLID).down("list-group"))||$(a._panelHTMLID).insert({bottom:d=new Element("div",
{"class":"list-group"})}),a._getListItem(b.items,d))}catch(e){$(a._panelHTMLID).insert({bottom:(new Element("div",{"class":"panel-body"})).update(a.getAlertBox("ERROR: ",e).addClassName("alert-danger"))})}},onComplete:function(){c.remove()}});return a},load:function(){$(this._panelHTMLID)&&this.showList();return this}};