var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_getTitleRowData:function(){return{id:"ID",dfrom:"From",dto:"To",dperiod:"Period",targetrevenue:"Revenue(Incl.)",targetprofit:"Profit(Incl.)"}},_bindSearchKey:function(){var a;a=this;$("searchPanel").getElementsBySelector("[search_field]").each(function(c){c.observe("keydown",function(b){a.keydown(b,function(){$(a.searchDivId).down("#searchBtn").click()})})});return this},_getEditPanel:function(a){var c,b,d;c=this;return b=(new Element("tr",{"class":"save-item-panel info"})).store("data",
a).insert({bottom:(new Element("td",{"class":"form-group"})).insert({bottom:new Element("input",{disabled:!0,"class":"form-control","save-item-panel":"id",value:a.id?a.id:""})})}).insert({bottom:(new Element("td",{"class":"form-group"})).insert({bottom:(new Element("div",{"class":"col-sm-12"})).insert({bottom:new Element("input",{required:!0,"class":"form-control input-sm datepicker",placeholder:"The start date of the sales period","save-item-panel":"dfrom",value:a.dfrom?a.dfrom:""})})})}).insert({bottom:(new Element("td",
{"class":"form-group"})).insert({bottom:(new Element("div",{"class":"col-sm-12"})).insert({bottom:new Element("input",{required:!0,"class":"form-control input-sm datepicker",placeholder:"The end date of the sales period","save-item-panel":"dto",value:a.dto?a.dto:""})})})}).insert({bottom:(new Element("td",{"class":"form-group"})).insert({bottom:new Element("input",{disabled:!0,"class":"form-control","save-item-panel":"dperiod",value:a.dperiod?a.dperiod:""})})}).insert({bottom:(new Element("td",{"class":"form-group"})).insert({bottom:new Element("input",
{required:!0,"class":"form-control",placeholder:"The revenue of the sales period",validate_currency:!0,"save-item-panel":"targetrevenue",value:a.targetrevenue?c._getCurrency(a.targetrevenue):""})}).observe("change",function(){c._currencyInputChanged(b.down("[save-item-panel=targetrevenue]"))})}).insert({bottom:(new Element("td",{"class":"form-group"})).insert({bottom:new Element("input",{required:!0,"class":"form-control",placeholder:"The profit of the sales period",validate_currency:!0,"save-item-panel":"targetprofit",
value:a.targetprofit?c._getCurrency(a.targetprofit):""})}).observe("change",function(){c._currencyInputChanged(b.down("[save-item-panel=targetprofit]"))})}).insert({bottom:(new Element("td",{"class":"text-right"})).insert({bottom:(new Element("span",{"class":"btn-group btn-group-sm"})).insert({bottom:(new Element("span",{"class":"btn btn-success",title:"Save"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-ok"})}).observe("click",function(){d=this;c._saveItem(d,$(d).up(".save-item-panel"),
"save-item-panel");jQuery(".item_row")&&jQuery(".alert")&&jQuery(".alert").remove()})}).insert({bottom:(new Element("span",{"class":"btn btn-danger",title:"Delete"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-remove"})}).observe("click",function(){a.id?$(this).up(".save-item-panel").replace(c._getResultRow(a).addClassName("item_row").writeAttribute("item_id",a.id)):$(this).up(".save-item-panel").remove()})})})})},_getResultRow:function(a,c){var b={me:this};b.tag=!0===b.isTitle?
"th":"td";b.isTitle=c||!1;b.row=(new Element("tr",{"class":!0===b.isTitle?"":"btn-hide-row"})).store("data",a).insert({bottom:(new Element(b.tag,{"class":"name col-xs-1"})).update(a.id)}).insert({bottom:(new Element(b.tag,{"class":"name col-xs-2"})).update(a.dfrom)}).insert({bottom:(new Element(b.tag,{"class":"name col-xs-2"})).update(a.dto)}).insert({bottom:(new Element(b.tag,{"class":"name col-xs-1"})).update(a.dperiod)}).insert({bottom:(new Element(b.tag,{"class":"name col-xs-2"})).update(!0===
b.isTitle?a.targetrevenue:b.me._getCurrency(a.targetrevenue))}).insert({bottom:(new Element(b.tag,{"class":"name col-xs-2"})).update(!0===b.isTitle?a.targetprofit:b.me._getCurrency(a.targetprofit))}).insert({bottom:(new Element(b.tag,{"class":"text-right col-xs-2 "})).update(!0===b.isTitle?(new Element("span",{"class":"btn btn-primary btn-xs",title:"New"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-plus"})}).insert({bottom:" NEW"}).observe("click",function(){$(this).up("thead").insert({bottom:b.newEditEl=
b.me._getEditPanel({})});b.newEditEl.down(".form-control[save-item-panel]").focus();b.newEditEl.down(".form-control[save-item-panel]").select();b.newEditEl.getElementsBySelector(".form-control[save-item-panel]").each(function(a){a.observe("keydown",function(a){b.me.keydown(a,function(){b.newEditEl.down(".btn-success span").click()});return!1})});b.me._bindDatePicker(b.newEditEl)}):(new Element("span",{"class":"btn-group btn-group-xs"})).insert({bottom:(new Element("span",{"class":"btn btn-default",
title:"Edit"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})}).observe("click",function(){$(this).up(".item_row").replace(b.editEl=b.me._getEditPanel(a));b.editEl.down(".form-control[save-item-panel]").focus();b.editEl.down(".form-control[save-item-panel]").select();b.editEl.getElementsBySelector(".form-control[save-item-panel]").each(function(a){a.observe("keydown",function(a){b.me.keydown(a,function(){b.editEl.down(".btn-success span").click()});return!1})});b.me._bindDatePicker(b.editEl)})}).insert({bottom:(new Element("span",
{"class":"btn btn-danger",title:"Delete"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-trash"})}).observe("click",function(){if(!confirm("Are you sure you want to delete this item?"))return!1;b.me._deleteItem(a)})}))});return b.row},_getCurrency:function(a,c,b,d,f){var h,g,e;h=isNaN(b=Math.abs(b))?2:b;c=void 0==c?"$":c;d=void 0==d?".":d;f=void 0==f?",":f;b=0>a?"-":"";g=parseInt(a=Math.abs(+a||0).toFixed(h))+"";e=3<(e=g.length)?e%3:0;return c+b+(e?g.substr(0,e)+f:"")+g.substr(e).replace(/(\d{3})(?=\d)/g,
"$1"+f)+(h?d+Math.abs(a-g).toFixed(h).slice(2):"")},_getValueFromCurrency:function(a){return a?(a+"").replace(/\s*/g,"").replace(/\$/g,"").replace(/,/g,""):""},_bindDatePicker:function(a){dfromCtl=a.down('[save-item-panel="dfrom"]');this._signRandID(dfromCtl);dtoCtl=a.down('[save-item-panel="dto"]');this._signRandID(dtoCtl);jQuery("#"+dfromCtl.id).datetimepicker({format:"YYYY-MM-DD"});jQuery("#"+dtoCtl.id).datetimepicker({format:"YYYY-MM-DD"});(a=jQuery("#"+dfromCtl.id).attr("value"))?jQuery("#"+
dfromCtl.id).data("DateTimePicker").date(new Date(a)):(jQuery("#"+dfromCtl.id).data("DateTimePicker").date(new Date),jQuery("#"+dfromCtl.id).attr("value",jQuery("#"+dfromCtl.id).data("DateTimePicker").date().utc().format("YYYY-MM-DD")));(a=jQuery("#"+dtoCtl.id).attr("value"))?jQuery("#"+dtoCtl.id).data("DateTimePicker").date(new Date(a)):(jQuery("#"+dtoCtl.id).data("DateTimePicker").date(new Date),jQuery("#"+dtoCtl.id).attr("value",jQuery("#"+dtoCtl.id).data("DateTimePicker").date().utc().format("YYYY-MM-DD")));
jQuery("#"+dfromCtl.id).data("DateTimePicker").maxDate(jQuery("#"+dtoCtl.id).data("DateTimePicker").date().utc().format("YYYY-MM-DD"));jQuery("#"+dtoCtl.id).data("DateTimePicker").minDate(jQuery("#"+dfromCtl.id).data("DateTimePicker").date().utc().format("YYYY-MM-DD"));jQuery("#"+dfromCtl.id).on("dp.change",function(a){jQuery("#"+dtoCtl.id).data("DateTimePicker").minDate(a.date)});jQuery("#"+dtoCtl.id).on("dp.change",function(a){jQuery("#"+dfromCtl.id).data("DateTimePicker").maxDate(a.date)});return this},
_markFormGroupError:function(a,c){var b={me:this};a.up(".form-group")&&(a.store("clearErrFunc",function(b){a.up(".form-group").removeClassName("has-error");jQuery("#"+a.id).tooltip("hide").tooltip("destroy").show()}).up(".form-group").addClassName("has-error"),b.me._signRandID(a),jQuery("#"+a.id).tooltip({trigger:"manual",placement:"auto",container:"body",placement:"bottom",html:!0,title:c,content:c}).tooltip("show"),$(a).observe("change",function(){b.func=$(a).retrieve("clearErrFunc");"function"===
typeof b.func&&b.func()}));return b.me},_currencyInputChanged:function(a){var c;if($F(a).blank())return!1;c=this._getValueFromCurrency($F(a));if(null===c.match(/^(-)?\d+(\.\d{1,4})?$/))return this._markFormGroupError(a,"Invalid currency format provided!"),!1;$(a).value=this._getCurrency(c);return!0}});