var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_getTitleRowData:function(){return{status:"Status",applyTo:"Apply To",raNo:"RMA No",description:"Description",totalValue:"Total Value",active:"Active",customer:{name:"Name"},order:{orderNo:"Order No"}}},_bindSearchKey:function(){var b,d,c;b=this;$$("#searchBtn").first().observe("click",function(a){$$("#showSearch").first().checked?b.getSearchCriteria().getResults(!0,b._pagination.pageSize):$$("#showSearch").first().click()});$("searchDiv").getElementsBySelector("[search_field]").each(function(a){a.observe("keydown",
function(a){b.keydown(a,function(){$(b.searchDivId).down("#searchBtn").click()})})});d=(new Element("input",{"class":"select2 form-control","data-placeholder":"search for a Customers",search_field:"cust.id"})).insert({bottom:(new Element("option")).update("")});$("searchDiv").down('[search_field="cust.id"]').replace(d);jQuery('.select2[search_field="cust.id"]').select2({allowClear:!0,hidden:!0,multiple:!0,ajax:{url:"/ajax/getCustomers",dataType:"json",delay:10,data:function(a){return{searchTxt:a,
storeId:jQuery("#storeId").attr("value"),userId:jQuery("#userId").attr("value")}},results:function(a){c=[];a.resultData.items.each(function(a){c.push({id:a.id,text:a.name,data:a})});return{results:c}},cache:!0},formatResult:function(a){return a?"<div value="+a.data.id+">"+a.data.name+"</div >":""},escapeMarkup:function(a){return a},minimumInputLength:1});d=(new Element("input",{"class":"select2 form-control","data-placeholder":"search for a Products",search_field:"pro.ids"})).insert({bottom:(new Element("option")).update("")});
$("searchDiv").down('[search_field="pro.ids"]').replace(d);jQuery('.select2[search_field="pro.ids"]').select2({allowClear:!0,hidden:!0,multiple:!0,ajax:{url:"/ajax/getProducts",dataType:"json",delay:10,data:function(a){return{searchTxt:a,pageNo:1,pageSize:10,userId:jQuery("#userId").attr("value")}},results:function(a){c=[];a.resultData.items.each(function(a){c.push({id:a.id,text:a.name,data:a})});return{results:c}},cache:!0},formatResult:function(a){return a?"<div value="+a.data.id+">"+a.data.name+
"</div >":""},escapeMarkup:function(a){return a},minimumInputLength:3});d=(new Element("select",{"class":"select2 form-control","data-placeholder":"search for a Status",search_field:"ra.status",multiple:!0})).insert({bottom:(new Element("option")).update("")});b._statusOptions.each(function(a){d.insert({bottom:(new Element("option",{value:a})).update(a)})});$("searchDiv").down('[search_field="ra.status"]').replace(d);jQuery('.select2[search_field="ra.status"]').select2({allowClear:!0});d=(new Element("input",
{"class":"select2 form-control","data-placeholder":"search for Suplliers",search_field:"po.supplierId"})).insert({bottom:(new Element("option")).update("")});$("searchDiv").down('[search_field="po.supplierId"]').replace(d);jQuery('.select2[search_field="po.supplierId"]').select2({allowClear:!0,hidden:!0,multiple:!0,ajax:{url:"/ajax/getSuppliers",dataType:"json",delay:10,data:function(a){return{searchTxt:a,storeId:jQuery("#storeId").attr("value"),userId:jQuery("#userId").attr("value")}},results:function(a){c=
[];a.resultData.items.each(function(a){c.push({id:a.id,text:a.name,data:a})});return{results:c}},cache:!0},formatResult:function(a){return a?"<div value="+a.data.id+">"+a.data.name+"</div >":""},escapeMarkup:function(a){return a},minimumInputLength:1});return this},_openEditPage:function(b){var d,c,a;d=this;jQuery.fancybox({width:"95%",height:"95%",autoScale:!1,autoDimensions:!1,fitToView:!1,autoSize:!1,type:"iframe",frameborder:"0",border:"0",seamless:"seamless",href:"/rma/"+(b&&b.id?b.id:"new")+
".html",beforeClose:function(){a=(c=$$("iframe.fancybox-iframe").first().contentWindow.pageJs)&&c._RMA&&c._RMA.id?d._getResultRow(c._RMA):null;null!==a&&(b&&b.id?$(d.resultDivId).down(".item_row[item_id="+b.id+"]")&&$(d.resultDivId).down(".item_row[item_id="+b.id+"]").replace(a):$(d.resultDivId).down("tbody").insert({top:a}))}});return d},_highlightSelectedRow:function(b){b=b.down(".glyphicon-plus")?"":$(b).up("[item_id]").retrieve("data");jQuery(".item_row.success").removeClass("success");jQuery("[item_id="+
b.id+"]").addClass("success")},_displaySelectedAddress:function(b){var d,c;d=$(b).up("[item_id]").retrieve("data");c=$(b).down("span").classList.contains("address-shipping");jQuery(".popover-loaded").popover("hide");jQuery(".item_row.success").removeClass("success");jQuery("[item_id="+d.id+"]").addClass("success");this._signRandID(b);jQuery("#"+b.id).hasClass("popover-loaded")||jQuery("#"+b.id).popover({title:'<div class="row"><div class="col-xs-10">Details for: '+d.name+'</div><div class="col-xs-2" style="cursor: pointer" href="javascript:void(0);" onclick="jQuery(\'#'+
b.id+"').popover('hide');\"><span class=\"pull-right glyphicon glyphicon-remove\" ></span></div></div>",html:!0,placement:function(){return c?"left":"right"},container:"body",trigger:"manual",viewport:{selector:".list-panel",padding:0},content:function(){return c?"<p>"+d.address.shipping.full+"</p>":"<p>"+d.address.billing.full+"</p>"},template:'<div class="popover" role="tooltip" style="max-width: none; z-index: 0;"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'}).addClass("popover-loaded");
jQuery("#"+b.id).popover("toggle");return this},_getResultRow:function(b,d){var c={me:this};countItems=0;b.raItems&&b.raItems.each(function(a){countItems=Number(countItems)+Number(a.qty)});c.tag=!0===c.isTitle?"th":"td";c.isTitle=d||!1;c.row=(new Element("tr",{"class":(!0===c.isTitle?"item_top_row":"btn-hide-row item_row")+(0==b.active?" danger":""),item_id:!0===c.isTitle?"":b.id})).store("data",b).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(b.raNo).setStyle("cursor: pointer;").observe("click",
function(){c.me._openEditPage(b)})}).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(b.description)}).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(c.isTitle?c.me._getTitleRowData().totalValue:c.me.getCurrency(b.totalValue))}).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(b.status)}).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(b.customer.name)}).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(b.order.orderNo?b.order.orderNo:
"")}).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(c.isTitle?"No of RMA NoteItems":b.raItems?countItems:"")}).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).setStyle("display: none;").insert({bottom:!0===c.isTitle?b.active:new Element("input",{type:"checkbox",disabled:!0,checked:b.active})})}).insert({bottom:(new Element(c.tag,{"class":"text-right col-xs-1"})).update(!0===c.isTitle?"":(new Element("span",{"class":"btn-group btn-group-xs"})).insert({bottom:(new Element("span",
{"class":"btn btn-default",title:"Edit"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})}).observe("click",function(){$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")});c.me._openEditPage(b)})}).insert({bottom:(new Element("span",{"class":"btn btn-danger",title:"Delete"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-trash"})}).observe("click",function(){if(!confirm("Are you sure you want to deactivate this item?"))return!1;b.active&&
c.me._deactivateItem(this);$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")})})})).observe("click",function(){c.me._highlightSelectedRow(this);$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")})})});return c.row},_getNextPageBtn:function(){var b;b=this;return(new Element("tfoot")).insert({bottom:(new Element("tr")).insert({bottom:(new Element("td",{colspan:"8","class":"text-center"})).insert({bottom:(new Element("span",{"class":"btn btn-primary","data-loading-text":"Fetching more results ..."})).update("Show More").observe("click",
function(){b._pagination.pageNo=1*b._pagination.pageNo+1;jQuery(this).button("loading");b.getResults()})})})})},_deactivateItem:function(b){var d,c,a;d=this;c=$(b).up("[item_id]");b=c.retrieve("data");d.postAjax(d.getCallbackId("deactivateItems"),{item_id:b.id},{onLoading:function(){c&&(c.toggleClassName("danger"),c.hide())},onSuccess:function(b,e){try{c.toggleClassName("danger");a=d.getResp(e,!1,!0);if(!a.item)throw"errror";$$('[item_id="'+a.item.id+'"]').first().replace(d._getResultRow(a.item,!1));
d._highlightSelectedRow($$('[item_id="'+a.item.id+'"]').first().down(".glyphicon.glyphicon-trash"))}catch(f){d.showModalBox('<span class="text-danger">ERROR</span>',f,!0)}}})}});