var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_getTitleRowData:function(){return{}},_loadDataPicker:function(){jQuery(".datepicker").datetimepicker({format:"DD/MM/YYYY"});return this},_searchProduct:function(){var b;jQuery('#searchDiv .select2[search_field="pro.ids"]').select2({allowClear:!0,hidden:!0,multiple:!0,ajax:{url:"/ajax/getProducts",dataType:"json",delay:10,data:function(a){return{searchTxt:a,pageNo:1,pageSize:10,userId:jQuery("#userId").attr("value")}},results:function(a){b=[];a.resultData.items.each(function(a){b.push({id:a.id,
text:a.sku,data:a})});return{results:b}},cache:!0},formatResult:function(a){return a?'<div class="row"><div class="col-xs-3 select2-word-break" style="word-wrap: break-word;">'+a.data.sku+'</div><div class="col-xs-9">'+a.data.name+"</div></div>":""},escapeMarkup:function(a){return a},minimumInputLength:3});return this},_searchCategories:function(){var b;jQuery('[search_field="pro.categories"]').select2({minimumInputLength:3,multiple:!0,ajax:{delay:250,url:"/ajax/getAll",type:"POST",data:function(a){return{searchTxt:"pro_cate.name like ?",
searchParams:["%"+a+"%"],entityName:"ProductCategory",pageNo:1}},results:function(a,c,d){b=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){b.push({id:a.id,text:a.namePath,data:a})});return{results:b}}},cache:!0,formatResult:function(a){return a?'<div class="row order_item"><div class="col-xs-12">'+a.data.namePath+"</div></div >":""},escapeMarkup:function(a){return a}});return this},_searchBrands:function(){var b;jQuery('[search_field="pro.manufacturerIds"]').select2({minimumInputLength:2,
multiple:!0,ajax:{delay:250,url:"/ajax/getAll",type:"POST",data:function(a){return{searchTxt:"man.name like ?",searchParams:["%"+a+"%"],entityName:"Manufacturer",pageNo:1}},results:function(a,c,d){b=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){b.push({id:a.id,text:a.name,data:a})});return{results:b}}},cache:!0,formatResult:function(a){return a?'<div class="row order_item"><div class="col-xs-12">'+a.data.name+"</div></div >":""},escapeMarkup:function(a){return a}});return this},
_searchPO:function(){var b;jQuery('#searchDiv .select2[search_field="po.id"]').select2({allowClear:!0,hidden:!0,multiple:!1,ajax:{url:"/ajax/getAll",dataType:"json",delay:10,data:function(a){return{searchTxt:"purchaseOrderNo like ? and storeId = ?",entityName:"PurchaseOrder",searchParams:["%"+a+"%",jQuery("#storeId").attr("value")],pageNo:1,pageSize:10,userId:jQuery("#userId").attr("value")}},results:function(a){b=[];a.resultData.items.each(function(a){b.push({id:a.id,text:a.purchaseOrderNo,data:a})});
return{results:b}},cache:!0},formatResult:function(a){return a?'<div class="row po_item"><div class="col-xs-3">'+a.data.purchaseOrderNo+'</div><div class="col-xs-2" order_status="'+a.data.status+'">'+a.data.status+'</div><div class="col-xs-6">'+a.data.supplier.name+"</div></div>":""},escapeMarkup:function(a){return a},minimumInputLength:3});return this},_bindSearchKey:function(){var b;b=this;$$("#searchBtn").first().observe("click",function(a){$$("#showSearch").first().checked?b.getSearchCriteria().getResults(!0,
b._pagination.pageSize):$$("#showSearch").first().click()});$("searchDiv").getElementsBySelector("[search_field]").each(function(a){a.observe("keydown",function(a){b.keydown(a,function(){$(b.searchDivId).down("#searchBtn").click()})})});b._searchProduct()._searchPO()._searchCategories()._searchBrands();return b},genReport:function(b){var a,c,d,e;a=this;c={};$$("[search_field]").each(function(a){c[a.readAttribute("search_field")]=$F(a)});a.postAjax(a.getCallbackId("genReportmBtn"),c,{onLoading:function(){jQuery(b).button("loading")},
onSuccess:function(b,c){try{if((d=a.getResp(c,!1,!0))&&d.url&&(e=window.open(d.url),!e))throw'You browser is blocking the popup window, please click <a class="btn btn-xs btn-primary" href="'+d.url+'" target="__BLANK">here</a> to open it manually.';}catch(f){a.showModalBox("<b>Error:</b>",'<b class="text-danger">'+f+"</b>")}},onComplete:function(){jQuery(b).button("reset")}});return a},_highlightSelectedRow:function(b){b=b.down(".glyphicon-plus")?"":$(b).up("[item_id]").retrieve("data");jQuery(".item_row.success").removeClass("success");
jQuery("[item_id="+b.id+"]").addClass("success")},_getLinkAddress:function(b,a,c){var d;c=c||[];d="";0<c.length&&(d="?",c.each(function(a){d=d+$H(a).keys()[0]+"="+$H(a).values()[0]+"&"}),d=d.substring(0,d.length-1));return"/"+b+(!0===jQuery.isNumeric(a)?"/"+a:"")+".html"+d},_getLink:function(b,a,c,d,e){d=d||null;return(new Element("a",{target:"_blank",href:null===d?this._getLinkAddress(b,a,e):d})).update(c)},_getResultRow:function(b,a){var c={me:this};c.tag=!0===c.isTitle?"th":"td";c.isTitle=a||!1;
c.row=(new Element("tr",{"class":(!0===c.isTitle?"item_top_row":"btn-hide-row item_row")+(0==b.active?" danger":""),item_id:!0===c.isTitle?"":b.id})).store("data",b).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(!0===c.isTitle?"Product SKU":c.me._getLink("product",b.product.id,b.product.sku))}).insert({bottom:(new Element(c.tag)).update(!0===c.isTitle?"Product Name":c.me._getLink("product",b.product.id,b.product.name))}).insert({bottom:(new Element(c.tag,{"class":"col-xs-2"})).update(!0===
c.isTitle?"Last Purchase Date":moment(c.me.loadUTCTime(b.lastPurchaseTime)).format("ll"))}).insert({bottom:(new Element(c.tag,{"class":"col-xs-1"})).update(!0===c.isTitle?"Qty":b.receivingItem.id?c.me._getLink("productqtylog",null,b.product.stockOnHand,null,[{productid:b.product.id}]):"N/A")}).insert({bottom:(new Element(c.tag,{"class":"col-xs-2"})).update(!0===c.isTitle?"Aged Days":moment().diff(moment(c.me.loadUTCTime(b.lastPurchaseTime)),"days"))});return c.row},_getNextPageBtn:function(){var b;
b=this;return(new Element("tfoot")).insert({bottom:(new Element("tr")).insert({bottom:(new Element("td",{colspan:"8","class":"text-center"})).insert({bottom:(new Element("span",{"class":"btn btn-primary","data-loading-text":"Fetching more results ..."})).update("Show More").observe("click",function(){b._pagination.pageNo=1*b._pagination.pageNo+1;jQuery(this).button("loading");b.getResults()})})})})}});