var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_getTitleRowData:function(){return{id:"ID",name:"Tier Name",percentage:"Tier Price(%)"}},_bindSearchKey:function(){var a;a=this;$("searchPanel").getElementsBySelector("[search_field]").each(function(c){c.observe("keydown",function(b){a.keydown(b,function(){$(a.searchDivId).down("#searchBtn").click()})})});return this},_getEditPanel:function(a){var c,b,d;c=this;return b=(new Element("tr",{"class":"save-item-panel info"})).store("data",a).insert({bottom:(new Element("td",
{"class":"form-group"})).insert({bottom:new Element("input",{disabled:!0,"class":"form-control","save-item-panel":"id",value:a.id?a.id:""})})}).insert({bottom:(new Element("td",{"class":"form-group"})).insert({bottom:new Element("input",{required:!0,"class":"form-control",placeholder:"The name of the tier","save-item-panel":"name",value:a.name?a.name:""})})}).insert({bottom:(new Element("td",{"class":"form-group"})).insert({bottom:new Element("input",{required:!0,"class":"form-control",validate_number:!0,
placeholder:"The price percetage of the tier","save-item-panel":"percentage",value:a.percentage?Number(a.percentage).toFixed(2):""})}).observe("change",function(){c._percentageInputChanged(b.down("[save-item-panel=percentage]"))})}).insert({bottom:(new Element("td",{"class":"text-right"})).insert({bottom:(new Element("span",{"class":"btn-group btn-group-sm"})).insert({bottom:(new Element("span",{"class":"btn btn-success",title:"Save"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-ok"})}).observe("click",
function(){d=this;c._saveItem(d,$(d).up(".save-item-panel"),"save-item-panel");jQuery(".item_row")&&jQuery(".alert")&&jQuery(".alert").remove()})}).insert({bottom:(new Element("span",{"class":"btn btn-danger",title:"Delete"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-remove"})}).observe("click",function(){a.id?$(this).up(".save-item-panel").replace(c._getResultRow(a).addClassName("item_row").writeAttribute("item_id",a.id)):$(this).up(".save-item-panel").remove()})})})})},_getResultRow:function(a,
c){var b={me:this};b.tag=!0===b.isTitle?"th":"td";b.isTitle=c||!1;b.row=(new Element("tr",{"class":!0===b.isTitle?"":"btn-hide-row"})).store("data",a).insert({bottom:(new Element(b.tag,{"class":"name col-xs-1"})).update(a.id)}).insert({bottom:(new Element(b.tag,{"class":"name col-xs-2"})).update(a.name)}).insert({bottom:(new Element(b.tag,{"class":"name col-xs-2"})).update(b.isTitle?a.percentage:a.percentage?Number(a.percentage).toFixed(2):"")}).insert({bottom:(new Element(b.tag,{"class":"text-right col-xs-2 "})).update(!0===
b.isTitle?(new Element("span",{"class":"btn btn-primary btn-xs",title:"New"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-plus"})}).insert({bottom:" NEW"}).observe("click",function(){$(this).up("thead").insert({bottom:b.newEditEl=b.me._getEditPanel({})});b.newEditEl.down(".form-control[save-item-panel]").focus();b.newEditEl.down(".form-control[save-item-panel]").select();b.newEditEl.getElementsBySelector(".form-control[save-item-panel]").each(function(a){a.observe("keydown",function(a){b.me.keydown(a,
function(){b.newEditEl.down(".btn-success span").click()});return!1})})}):(new Element("span",{"class":"btn-group btn-group-xs"})).insert({bottom:(new Element("span",{"class":"btn btn-default",title:"Edit"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})}).observe("click",function(){$(this).up(".item_row").replace(b.editEl=b.me._getEditPanel(a));b.editEl.down(".form-control[save-item-panel]").focus();b.editEl.down(".form-control[save-item-panel]").select();b.editEl.getElementsBySelector(".form-control[save-item-panel]").each(function(a){a.observe("keydown",
function(a){b.me.keydown(a,function(){b.editEl.down(".btn-success span").click()});return!1})})})}).insert({bottom:(new Element("span",{"class":"btn btn-danger",title:"Delete"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-trash"})}).observe("click",function(){if(!confirm("Are you sure you want to delete this item?"))return!1;b.me._deleteItem(a)})}))});return b.row},_markFormGroupError:function(a,c){var b={me:this};a.up(".form-group")&&(a.store("clearErrFunc",function(b){a.up(".form-group").removeClassName("has-error");
jQuery("#"+a.id).tooltip("hide").tooltip("destroy").show()}).up(".form-group").addClassName("has-error"),b.me._signRandID(a),jQuery("#"+a.id).tooltip({trigger:"manual",placement:"auto",container:"body",placement:"bottom",html:!0,title:c,content:c}).tooltip("show"),$(a).observe("change",function(){b.func=$(a).retrieve("clearErrFunc");"function"===typeof b.func&&b.func()}));return b.me},_percentageInputChanged:function(a){}});